/* (Beta) Export of data model TrackedManeuver of the subject dataModel.MarineTransport 
for a PostgreSQL database. Pending translation of enumerations and multityped attributes */
CREATE TYPE TrackedManeuver_type AS ENUM ('TrackedManeuver');

CREATE TABLE TrackedManeuver (
    address JSON,
    alternateName TEXT,
    amendedOnMooringLocation TEXT,
    anchoringAnchorUpDate TIMESTAMP,
    anchoringDate TIMESTAMP,
    anchoringLocation JSON,
    anchoringZone TEXT,
    areaServed TEXT,
    dataProvider TEXT,
    dateCreated TIMESTAMP,
    dateModified TIMESTAMP,
    description TEXT,
    durationHours NUMERIC,
    endDate TIMESTAMP,
    id TEXT PRIMARY KEY,
    location JSON,
    maneuverCode TEXT,
    maneuverType TEXT,
    mooringCablesNumber NUMERIC,
    mooringChangeCablesNumber NUMERIC,
    mooringChangeFirstLandCableDate TIMESTAMP,
    mooringChangeInitialLocation TEXT,
    mooringChangeLastCableDate TIMESTAMP,
    mooringChangeLastLocation TEXT,
    mooringChangeNoraysFrom NUMERIC,
    mooringChangeNoraysTo NUMERIC,
    mooringChangeSide TEXT,
    mooringFirstCableDate TIMESTAMP,
    mooringLocation TEXT,
    mooringNoraysFrom NUMERIC,
    mooringNoraysTo NUMERIC,
    mooringSide TEXT,
    name TEXT,
    observations TEXT,
    observedDate TIMESTAMP,
    othersLocation JSON,
    othersType TEXT,
    othersZone TEXT,
    owner JSON,
    pilotageDisembarkDate TIMESTAMP,
    pilotageDisembarkLocation TEXT,
    pilotageEmbarkDate TIMESTAMP,
    pilotageEmbarkLocation TEXT,
    pilotageExempt TEXT,
    pilotageObservations TEXT,
    pilotagePilots TEXT,
    portCallCode TEXT,
    refPortCallId TEXT,
    refTugServiceId TEXT,
    seeAlso JSON,
    source TEXT,
    startDate TIMESTAMP,
    tugboatsNumber NUMERIC,
    tugboatsObservations TEXT,
    type TrackedManeuver_type,
    undockingLastCableDate TIMESTAMP,
    undockingLocation TEXT
);