---
# Copyleft (c) 2022 Contributors to Smart Data Models initiative
#


components:
  schemas:
    KeyVessel:
      $ref: "https://smart-data-models.github.io/dataModel.MarineTransport/KeyVessel/model.yaml#KeyVessel"
info:
  description: |
    The data model is intended to provide information about key vessels that a port community must focus his work on next days. It allows to represent the properties of each vessel: static and dynamic information
  title: KeyVessel
  version: "0.0.1"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - KeyVessel
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.MarineTransport/KeyVessel/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.MarineTransport/KeyVessel/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld