/* (Beta) Export of data model Facility of the subject dataModel.MarineTransport for a PostgreSQL database. Pending translation of enumerations and multityped attributes */
CREATE TYPE facilityType_type AS ENUM ('BERTH', 'TERMINAL', 'ANCHORAGE', 'OTHER');
CREATE TYPE mrn_type AS ENUM ('PortCall');
CREATE TYPE Facility_type AS ENUM ('Facility');
CREATE TABLE Facility (
  "address" JSON,
  "alternateName" TEXT,
  "areaServed" TEXT,
  "bollardCodes" JSON,
  "closed" BOOLEAN,
  "dataProvider" TEXT,
  "dateCreated" TIMESTAMP,
  "dateModified" TIMESTAMP,
  "deadweight" NUMERIC,
  "description" TEXT,
  "displacement" NUMERIC,
  "facilityCode" TEXT,
  "facilityName" TEXT,
  "facilityType" facilityType_type,
  "firstBollard" NUMERIC,
  "id" TEXT PRIMARY KEY,
  "lastBollard" NUMERIC,
  "latitude" JSON,
  "location" JSON,
  "longitude" NUMERIC,
  "maxBeam" NUMERIC,
  "maxDraught" NUMERIC,
  "maxLoa" NUMERIC,
  "minimumProbe" NUMERIC,
  "minimumProbeDate" TIMESTAMP,
  "modifiedDate" TIMESTAMP,
  "mrn" mrn_type,
  "name" TEXT,
  "navigationSector" TEXT,
  "owner" JSON,
  "planningGroup" TEXT,
  "portCode" TEXT,
  "remarks" TEXT,
  "seeAlso" JSON,
  "source" TEXT,
  "terminal" TEXT,
  "terminalRef" TEXT,
  "type" Facility_type
);